[book]
authors = ["Glyn Normington"]
language = "en"
multilingual = false
src = "src"
title = "The Book of Modern C++"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/maverickcasanova/cpp-book"
site-url = "https://github.com/maverickcasanova/cpp-book/"
